FROM maven:3.8.7-openjdk-18-slim

WORKDIR /app

COPY . /app

RUN mvn clean package

CMD ["java", "-cp", "target/Beadando_Informacios_rendszerek-1.0-SNAPSHOT.jar:target/dependency/*", "org.colorQueue.ColorMessageProducer"]
