FROM maven:3.8.7-openjdk-18-slim

WORKDIR /app

# A teljes projekt átmásolása a konténerbe
COPY . /app

# Maven build
RUN mvn clean install

# A RedMessageConsumer osztály futtatása
CMD ["java", "-jar", "target/red-consumer2.jar"]
